name: Be Brave
favicon: null
layout_spectrum: 0.9259345906320959
typography_spectrum: 0.7257520980201662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6782501202542335
  lightness: 0.6437729150056839
  saturation: 0.7674428678583354
  rhythmicContrast: 0.6251543497201055
purpose: []
