name: Be Brave
favicon: null
layout_spectrum: 0.24609
typography_spectrum: 0.4987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e2df'
    - '#b88e76'
    - '#c0b5af'
    - '#252229'
    - '#964534'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
